Foundry imporvements (#1011)

diff --git a/packages/foundry/Makefile b/packages/foundry/Makefile
--- a/packages/foundry/Makefile
+++ b/packages/foundry/Makefile
@@ -1,8 +1,11 @@
 .PHONY: build deploy generate-abis verify-keystore account chain compile deploy-verify flatten fork format lint test verify
 
+DEPLOY_SCRIPT ?= script/Deploy.s.sol
+
 # setup wallet for anvil
 setup-anvil-wallet:
 	shx rm ~/.foundry/keystores/scaffold-eth-default 2>/dev/null; \
+	shx rm -rf broadcast/Deploy.s.sol/31337
 	cast wallet import --private-key 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6 --unsafe-password 'localhost' scaffold-eth-default
 
 # Start local chain
@@ -15,14 +18,22 @@ fork: setup-anvil-wallet
 
 # Build the project
 build:
-	forge build --build-info --build-info-path out/build-info/
+	forge build --via-ir --build-info --build-info-path out/build-info/
 
-# Deploy the project
+# Deploy the contracts
 deploy:
+	@if [ ! -f "$(DEPLOY_SCRIPT)" ]; then \
+		echo "Error: Deploy script '$(DEPLOY_SCRIPT)' not found"; \
+		exit 1; \
+	fi
 	@if [ "$(RPC_URL)" = "localhost" ]; then \
-		forge script script/Deploy.s.sol --rpc-url localhost --password localhost --broadcast --legacy --ffi; \
+		if [ "$(ETH_KEYSTORE_ACCOUNT)" = "scaffold-eth-default" ]; then \
+			forge script $(DEPLOY_SCRIPT) --rpc-url localhost --password localhost --broadcast --legacy --ffi; \
+		else \
+			forge script $(DEPLOY_SCRIPT) --rpc-url localhost --broadcast --legacy --ffi; \
+		fi \
 	else \
-		forge script script/Deploy.s.sol --rpc-url $(RPC_URL) --broadcast --legacy --ffi; \
+		forge script $(DEPLOY_SCRIPT) --rpc-url $(RPC_URL) --broadcast --legacy --ffi; \
 	fi
 
 # Build and deploy target
@@ -35,9 +46,9 @@ generate-abis:
 verify-keystore:
 	if grep -q "scaffold-eth-default" .env; then \
 		cast wallet address --password localhost; \
-  else \
+	else \
 		cast wallet address; \
-  fi
+	fi
 
 # List account
 account:
@@ -58,10 +69,18 @@ compile:
 
 # Deploy and verify
 deploy-verify:
+	@if [ ! -f "$(DEPLOY_SCRIPT)" ]; then \
+		echo "Error: Deploy script '$(DEPLOY_SCRIPT)' not found"; \
+		exit 1; \
+	fi
 	@if [ "$(RPC_URL)" = "localhost" ]; then \
-		forge script script/Deploy.s.sol --rpc-url localhost --password localhost --broadcast --legacy --ffi --verify; \
+		if [ "$(ETH_KEYSTORE_ACCOUNT)" = "scaffold-eth-default" ]; then \
+			forge script $(DEPLOY_SCRIPT) --rpc-url localhost --password localhost --broadcast --legacy --ffi --verify; \
+		else \
+			forge script $(DEPLOY_SCRIPT) --rpc-url localhost --broadcast --legacy --ffi --verify; \
+		fi \
 	else \
-		forge script script/Deploy.s.sol --rpc-url $(RPC_URL) --broadcast --legacy --ffi --verify; \
+		forge script $(DEPLOY_SCRIPT) --rpc-url $(RPC_URL) --broadcast --legacy --ffi --verify; \
 	fi
 	node scripts-js/generateTsAbis.js
 
@@ -82,4 +101,3 @@ verify:
 	forge script script/VerifyAll.s.sol --ffi --rpc-url $(RPC_URL)
 
 build-and-verify: build verify
-
